name: wifipulse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:

  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_heat_map: ^1.2.1
  geolocator: ^14.0.0  
  permission_handler: ^12.0.0+1
  syncfusion_flutter_gauges: ^29.1.38
  cupertino_icons: ^1.0.8
  wifi_scan: ^0.4.1+2
  device_info_plus: ^11.3.3
  network_info_plus: ^6.1.3
  webview_flutter: ^4.11.0
  network_speed: ^0.0.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
